spring.application.name=postsService

server.port = 9020

spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update