spring.application.name=userService

server.servlet.context-path=/api/v1/users
server.port = 9021

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update